// src/components/ListPage/ListPage.tsx
import { useEffect, useMemo, useRef, useState, type JSX } from "react";
import { Box, Button, Container, IconButton, TextField, Typography } from "@mui/material";
import CheckBoxIcon from "@mui/icons-material/CheckBox";
import CheckBoxOutlineBlankIcon from "@mui/icons-material/CheckBoxOutlineBlank";
import ProfileItem from "../ProfileItem/ProfileItem";
import ArtworkCountSortButton from "./components/ArtworkCountSortButton/ArtworkCountSortButton";
import styles from "./ListPage.styles";
import type { Character, Artist, SortOrder } from "../../types/data";

interface Props {
    mode: typeof MODE_CHARACTER | typeof MODE_ARTIST;
    characters?: Character[];
    artists?: Artist[];
}

const MODE_CHARACTER = "character";
const MODE_ARTIST = "artist";
const BASE_URL = import.meta.env.BASE_URL;
const PAGE_SIZE = 25;



const ListPage = ({ mode, characters, artists }: Props): JSX.Element => {
    const title = mode === MODE_CHARACTER ? "Character List" : "Artist List";
    const ariaLabel = mode === MODE_CHARACTER ? "Search Characters" : "Search Artists";

    if ((mode === MODE_CHARACTER && !characters) || (mode === MODE_ARTIST && !artists)) {
        throw new Error(`${mode} data prop is required`);
    }

    const allItems = useMemo(() => (mode === MODE_CHARACTER ? characters! : artists!), [mode, characters, artists]);

    const [searchInput, setSearchInput] = useState("");
    const [searchQuery, setSearchQuery] = useState("");
    const [isSelectMode, setIsSelectMode] = useState(false);
    const [selectedItems, setSelectedItems] = useState<string[]>([]);
    const [sortOrder, setSortOrder] = useState<SortOrder>(mode === MODE_ARTIST ? "desc" : "none");
    const [visibleCount, setVisibleCount] = useState(PAGE_SIZE);
    const loadMoreRef = useRef<HTMLDivElement | null>(null);



    const searchedItems = useMemo(() => {
        if (!searchQuery) return allItems;
        return allItems.filter(({ id, name }) => [id, name].some(field => field.toLowerCase().includes(searchQuery.toLowerCase())));

    }, [allItems, searchQuery]);

    const sortedItems = useMemo(() => {
        const compare = (a: Character | Artist, b: Character | Artist) => {
            if (sortOrder === "none") return mode === MODE_ARTIST ? a.id.localeCompare(b.id) : 0;
            const primaryDiff = sortOrder === "asc"
                ? a.artworkCount - b.artworkCount
                : b.artworkCount - a.artworkCount;
            if (primaryDiff !== 0) return primaryDiff;
            const [aSecondary, bSecondary] = mode === MODE_CHARACTER
                ? [(a as Character).artistCount, (b as Character).artistCount]
                : [(a as Artist).characterCount, (b as Artist).characterCount];
            return sortOrder === "asc" ? aSecondary - bSecondary : bSecondary - aSecondary;
        };
        return [...searchedItems].sort(compare);

    }, [searchedItems, sortOrder, mode]);



    const toggleSortOrder = () => {
        setSortOrder(prev => (prev === "none" ? "desc" : prev === "desc" ? "asc" : "none"));
    };

    const handleToggleSelectMode = () => {
        if (isSelectMode && selectedItems.length === 0) {
            setIsSelectMode(false);
        } else {
            setIsSelectMode(!isSelectMode);
        }
    };

    const handleNavigateSelected = () => {
        if (selectedItems.length === 0) return;
        const queryKey = mode === MODE_CHARACTER ? "characters" : "artists";
        const url = `${BASE_URL}gallery?${queryKey}=${selectedItems.join(",")}`;
        window.location.href = url;
    };

    const handleToggleItem = (id: string) => {
        setSelectedItems(prev =>
            prev.includes(id) ? prev.filter(i => i !== id) : [...prev, id]
        );
    };

    const renderListItems = (): JSX.Element[] => {
        return sortedItems.slice(0, visibleCount).map((item) => {
            const id = item.id;
            const name = item.name;
            const artworkCountText = `${item.artworkCount} artwork${item.artworkCount !== 1 ? "s" : ""}`;
            const extraCountText = mode === MODE_CHARACTER
                ? `${(item as Character).artistCount} artist${(item as Character).artistCount !== 1 ? "s" : ""}`
                : `${(item as Artist).characterCount} character${(item as Artist).characterCount !== 1 ? "s" : ""}`;
            const imageUrl = `${BASE_URL}${item.portrait}`;

            const selected = selectedItems.includes(id);
            const galleryLink = `${BASE_URL}gallery?${mode === MODE_CHARACTER ? "characters" : "artist"}=${selectedItems.join(",") || id}`;

            return (
                <ProfileItem
                    key={id}
                    name={name}
                    imageUrl={imageUrl}
                    description1={artworkCountText}
                    description2={extraCountText}
                    link={isSelectMode ? undefined : galleryLink}
                    isSelectMode={isSelectMode}
                    isSelected={selected}
                    onToggleSelect={() => handleToggleItem(id)}
                />
            );
        });
    };



    useEffect(() => {
        const timeout = setTimeout(() => setSearchQuery(searchInput), 300);
        return () => clearTimeout(timeout);
    }, [searchInput]);

    useEffect(() => {
        const observer = new IntersectionObserver(
            (entries) => {
                if (entries[0].isIntersecting) {
                    setVisibleCount((prev) => Math.min(prev + PAGE_SIZE, sortedItems.length));
                }
            },
            { rootMargin: "100px" }
        );
        const current = loadMoreRef.current;
        if (current) observer.observe(current);
        return () => { if (current) observer.unobserve(current); };
    }, [sortedItems]);

    useEffect(() => { setVisibleCount(PAGE_SIZE); }, [searchQuery, sortOrder]);



    return (
        <Container maxWidth="xl" sx={styles.container}>
            <Box sx={styles.box}>
                <Typography variant="h4" component="h2" sx={styles.typography}>{title}</Typography>
                <TextField
                    label="Search by ID or Name"
                    variant="outlined"
                    value={searchInput}
                    sx={styles.textField}
                    onChange={(e) => setSearchInput(e.target.value)}
                    slotProps={{ input: { "aria-label": ariaLabel } }}
                />
                {mode === MODE_CHARACTER && (
                    <Box sx={{ display: 'flex', alignItems: 'center', mr: 2 }}>
                        <Box sx={{ display: 'flex', alignItems: 'center', cursor: 'pointer' }} onClick={handleToggleSelectMode}>
                            <IconButton
                                color={isSelectMode ? "primary" : "default"}
                                aria-label="Toggle multi-select mode"
                            >
                                {isSelectMode ? <CheckBoxIcon /> : <CheckBoxOutlineBlankIcon />}
                            </IconButton>
                            <Typography
                                variant="body2"
                                color={isSelectMode ? "primary" : "text.secondary"}
                                sx={{ userSelect: "none" }}
                            >
                                {isSelectMode
                                    ? selectedItems.length > 0
                                        ? `${selectedItems.length} Selected`
                                        : "Multi-Select ON"
                                    : "Multi-Select OFF"}
                            </Typography>
                        </Box>

                        {isSelectMode && selectedItems.length > 0 && (
                            <Button
                                variant="contained"
                                color="primary"
                                sx={{ ml: 2 }}
                                onClick={handleNavigateSelected}
                            >
                                View Selected
                            </Button>
                        )}
                    </Box>
                )}

                <ArtworkCountSortButton sortOrder={sortOrder} onToggleSortOrder={toggleSortOrder} />
            </Box>
            <Box component="ul" sx={styles.listGrid}>
                {renderListItems()}
            </Box>
            {visibleCount < sortedItems.length && <Box ref={loadMoreRef} sx={{ height: "1px" }} />}
        </Container>
    );
};

export default ListPage;

// src/lib/components/ListPage.svelte
<script lang="ts">
    import { base } from '$app/paths';
    import ProfileItem from './ProfileItem.svelte';
    import type { Artist, Character, SortOrder } from '../../types/data';

    export let mode: 'character' | 'artist';
    export let characters: Character[] = [];
    export let artists: Artist[] = [];

    const pageSize = 50;
    let searchInput = '';
    let isSelectMode = false;
    let selectedItems: string[] = [];
    let sortOrder: SortOrder = mode === 'artist' ? 'desc' : 'none';
    let visibleCount = pageSize;

    $: title = mode === 'character' ? 'Character List' : 'Artist List';
    $: allItems = mode === 'character' ? characters : artists;
    $: searchedItems = searchInput
        ? allItems.filter(({ id, name }) => [id, name].some(field => field.toLowerCase().includes(searchInput.toLowerCase())))
        : allItems;
    $: sortedItems = [...searchedItems].sort(compareItems);
    $: visibleItems = sortedItems.slice(0, visibleCount);

    function compareItems(a: Character | Artist, b: Character | Artist) {
        if (sortOrder === 'none') return mode === 'artist' ? a.id.localeCompare(b.id) : 0;
        const primaryDiff = sortOrder === 'asc'
            ? a.artworkCount - b.artworkCount
            : b.artworkCount - a.artworkCount;
        if (primaryDiff !== 0) return primaryDiff;
        const aSecondary = mode === 'character' ? (a as Character).artistCount : (a as Artist).characterCount;
        const bSecondary = mode === 'character' ? (b as Character).artistCount : (b as Artist).characterCount;
        return sortOrder === 'asc' ? aSecondary - bSecondary : bSecondary - aSecondary;
    }

    function toggleSortOrder() {
        sortOrder = sortOrder === 'none' ? 'desc' : sortOrder === 'desc' ? 'asc' : 'none';
    }

    function toggleItem(id: string) {
        selectedItems = selectedItems.includes(id)
            ? selectedItems.filter(item => item !== id)
            : [...selectedItems, id];
    }

    function selectedGalleryUrl(id: string) {
        const key = mode === 'character' ? 'characters' : 'artist';
        return `${base}/gallery/?${key}=${selectedItems.join(',') || id}`;
    }
</script>

<svelte:head>
    <title>{title} | Touhou Translations</title>
</svelte:head>

<section class="container">
    <div class="toolbar">
        <h1>{title}</h1>
        <label>
            <span class="visually-hidden">Search by ID or Name</span>
            <input bind:value={searchInput} placeholder="Search by ID or Name" aria-label={`Search ${title}`} />
        </label>
        {#if mode === 'character'}
            <div class="select-tools">
                <button
                    type="button"
                    class:active={isSelectMode}
                    aria-pressed={isSelectMode}
                    on:click={() => {
                        if (isSelectMode && selectedItems.length === 0) isSelectMode = false;
                        else isSelectMode = !isSelectMode;
                    }}
                >
                    {isSelectMode ? `${selectedItems.length || 'Multi'} Selected` : 'Multi-Select OFF'}
                </button>
                {#if isSelectMode && selectedItems.length > 0}
                    <a class="primary" href={`${base}/gallery/?characters=${selectedItems.join(',')}`}>View Selected</a>
                {/if}
            </div>
        {/if}
        <button type="button" class="sort" on:click={toggleSortOrder} aria-pressed={sortOrder !== 'none'}>
            {sortOrder === 'none' ? 'Sort' : sortOrder === 'desc' ? 'Count ↓' : 'Count ↑'}
        </button>
    </div>

    <ul class="grid">
        {#each visibleItems as item (item.id)}
            <ProfileItem
                name={item.name}
                imageUrl={`${base}/${item.portrait}`}
                description1={`${item.artworkCount} artwork${item.artworkCount === 1 ? '' : 's'}`}
                description2={mode === 'character'
                    ? `${(item as Character).artistCount} artist${(item as Character).artistCount === 1 ? '' : 's'}`
                    : `${(item as Artist).characterCount} character${(item as Artist).characterCount === 1 ? '' : 's'}`}
                link={isSelectMode ? undefined : selectedGalleryUrl(item.id)}
                isSelectMode={isSelectMode}
                isSelected={selectedItems.includes(item.id)}
                onToggleSelect={() => toggleItem(item.id)}
                size="large"
            />
        {/each}
    </ul>

    {#if visibleCount < sortedItems.length}
        <button class="load-more" type="button" on:click={() => visibleCount += pageSize}>Load More</button>
    {/if}
</section>

<style>
    .container {
        width: min(1600px, 100%);
        padding: 0.5rem 0 1.5rem;
        margin: 0 auto;
    }

    .toolbar {
        display: flex;
        flex-wrap: wrap;
        align-items: center;
        justify-content: space-between;
        gap: 0.85rem;
        padding: 1rem;
        margin-bottom: 1.25rem;
        background: rgba(255, 255, 255, 0.78);
        border: 1px solid var(--color-border);
        border-radius: var(--radius-lg);
        box-shadow: var(--shadow-sm);
        backdrop-filter: blur(10px);
    }

    h1 {
        margin: 0;
        color: var(--color-ink);
        font-size: clamp(1.45rem, 2.8vw, 2rem);
        line-height: 1.15;
    }

    label {
        flex: 1 1 260px;
        max-width: 440px;
    }

    input {
        width: 100%;
        min-height: 44px;
        padding: 0.65rem 0.85rem;
        color: var(--color-ink);
        background: var(--color-surface);
        border: 1px solid var(--color-border-strong);
        border-radius: var(--radius-md);
    }

    button,
    .primary {
        display: inline-flex;
        min-height: 40px;
        align-items: center;
        gap: 0.45rem;
        padding: 0.5rem 0.8rem;
        color: var(--color-muted);
        text-decoration: none;
        cursor: pointer;
        background: transparent;
        border: 1px solid var(--color-border);
        border-radius: 8px;
    }

    button.active,
    .primary {
        color: var(--color-primary);
        background: var(--color-primary-soft);
        border-color: rgba(180, 35, 59, 0.24);
    }

    .select-tools {
        display: flex;
        align-items: center;
        gap: 0.75rem;
    }

    .grid {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
        gap: 1.4rem;
        padding: 0;
        margin: 0;
        list-style: none;
    }

    .load-more {
        margin: 1.25rem auto 0;
    }

    .visually-hidden {
        position: absolute;
        width: 1px;
        height: 1px;
        padding: 0;
        overflow: hidden;
        clip: rect(0, 0, 0, 0);
        white-space: nowrap;
        border: 0;
    }

    @media (min-width: 1280px) {
        .grid {
            grid-template-columns: repeat(4, minmax(0, 1fr));
        }
    }

    @media (max-width: 640px) {
        .container {
            padding: 1rem;
        }

        .toolbar {
            align-items: stretch;
            justify-content: flex-start;
            padding: 0.85rem;
        }

        .grid {
            grid-template-columns: 1fr;
            gap: 0.85rem;
        }

        h1,
        label {
            flex-basis: 100%;
            max-width: none;
        }
    }
</style>
